#pragma once
#include "lvgl.h"
LV_FONT_DECLARE(luna_cjk_16);
LV_FONT_DECLARE(luna_cjk_28);
LV_FONT_DECLARE(luna_cjk_10);
LV_FONT_DECLARE(luna_cjk_13);
LV_FONT_DECLARE(luna_cjk_18);
LV_FONT_DECLARE(luna_cjk_20);
LV_FONT_DECLARE(luna_digits_86);
LV_FONT_DECLARE(luna_digits_101);
extern const lv_image_dsc_t luna_icon_moon_24;
extern const lv_image_dsc_t luna_icon_moon_30;
extern const lv_image_dsc_t luna_icon_moon_33;
extern const lv_image_dsc_t luna_icon_moon_135;
extern const lv_image_dsc_t luna_icon_play_24;
extern const lv_image_dsc_t luna_icon_play_30;
extern const lv_image_dsc_t luna_icon_pause_24;
extern const lv_image_dsc_t luna_icon_pause_30;
extern const lv_image_dsc_t luna_icon_prev_24;
extern const lv_image_dsc_t luna_icon_next_24;
extern const lv_image_dsc_t luna_icon_volume_24;
extern const lv_image_dsc_t luna_icon_mute_24;
extern const lv_image_dsc_t luna_icon_code_24;
extern const lv_image_dsc_t luna_icon_clock_24;
extern const lv_image_dsc_t luna_icon_weather_24;
extern const lv_image_dsc_t luna_icon_computer_24;
extern const lv_image_dsc_t luna_icon_chev_24;
extern const lv_image_dsc_t luna_icon_bt_24;
extern const lv_image_dsc_t luna_icon_wifi_24;
extern const lv_image_dsc_t luna_cloud;
extern const lv_image_dsc_t luna_sun;
extern const lv_image_dsc_t luna_star_warm;
extern const lv_image_dsc_t luna_star_cool;
extern const lv_image_dsc_t luna_pet_0;
extern const lv_image_dsc_t luna_pet_left_0;
extern const lv_image_dsc_t luna_pet_1;
extern const lv_image_dsc_t luna_pet_left_1;
extern const lv_image_dsc_t luna_pet_2;
extern const lv_image_dsc_t luna_pet_left_2;
extern const lv_image_dsc_t luna_pet_3;
extern const lv_image_dsc_t luna_pet_left_3;
extern const lv_image_dsc_t luna_pet_4;
extern const lv_image_dsc_t luna_pet_5;
extern const lv_image_dsc_t luna_pet_6;
extern const lv_image_dsc_t luna_pet_7;
extern const lv_image_dsc_t luna_backdrop;
